ballot_source/sources/urls.py
from django.urls import path

# from django.views.generic import TemplateView
from .views import (
    DiffView,
    ManageSubscriptions,
    ScrapeView,
    SourceDetailView,
    SourceEditView,
    SourceFormView,
    SourceListView,
    SubscriptionList,
)

app_name = "sources"
urlpatterns = [
    path("", SourceListView.as_view(), name="index"),
    path("<int:pk>", SourceDetailView.as_view(), name="detail"),
    path("subscribe", ManageSubscriptions.as_view(), name="subscribe"),
    path("new", SourceFormView.as_view(), name="new"),
    path("<int:pk>/edit", SourceEditView.as_view(), name="edit"),
    path("<int:source_pk>/<int:pk>", DiffView.as_view(), name="diff"),
    path("scrape/<int:pk>", ScrapeView.as_view(), name="scrape"),
    path("scrape", ScrapeView.as_view(), name="scrape"),
    path("subscriptions", SubscriptionList.as_view(), name="subscriptions"),
]

ballot_source/users/urls.py
from django.urls import path

from ballot_source.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("ballot_source.users.urls", namespace="users")),
    path("sources/", include("ballot_source.sources.urls", namespace="sources")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ballot_source/sources/models.py
import difflib
import re

import requests
from bs4 import BeautifulSoup
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils import timezone

from .states import STATES


class Source(models.Model):
    SOURCE_TYPE_CHOICES = [
        ("STATE", "State"),
        ("COUNTY", "County"),
        ("LOCATIONS", "Locations"),
        ("OTHER", "Other"),
    ]

    created = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(
        get_user_model(),
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="sources_created",
    )
    updated = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(
        get_user_model(),
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="sources_updated",
    )
    last_checked = models.DateTimeField(null=True, blank=True)
    url = models.URLField(unique=True)
    source_type = models.CharField(
        choices=SOURCE_TYPE_CHOICES, default="OTHER", max_length=20
    )
    fips = models.CharField(max_length=5, blank=True, null=True)
    state = models.CharField(choices=STATES, blank=True, null=True, max_length=2)
    user_subscription = models.ManyToManyField(
        to=get_user_model(), related_name="subscribed_diffs"
    )

    def __str__(self):
        return f"{self.source_type}: {self.url}"

    def save(self, *args, **kwargs):
        # Check for duplicate url
        if not self.pk:
            Source.validate_url(self.url, self.pk)

        pull_source = self.pk is None
        super(Source, self).save(*args, **kwargs)
        if pull_source:
            SourceDetail.objects.create(source=self)

    def scrape(self):
        SourceDetail.objects.create(source=self)

    @property
    def last_changed(self):
        return SourceDetail.objects.filter(source=self).order_by("-date_pulled").first()

    def get_absolute_url(self):
        return reverse("sources:detail", args=[str(self.id)])

    @staticmethod
    def strip_url(url):
        stripped_url = re.sub(r"https?://", "", url).replace("www.", "")
        stripped_url = re.sub(r"/$", "", stripped_url)
        return stripped_url

    @classmethod
    def validate_url(cls, url, pk=None):
        similar_urls = Source.objects.filter(url__contains=cls.strip_url(url)).exclude(
            pk=pk
        )
        similar_urls = [
            cls.strip_url(s.url)
            for s in similar_urls
            if cls.strip_url(s.url) == cls.strip_url(url)
        ]
        if len(similar_urls):
            raise ValidationError(
                "This url has already been entered", params={"url": url},
            )


class SourceDetail(models.Model):
    source = models.ForeignKey(Source, on_delete=models.CASCADE, related_name="details")
    date_pulled = models.DateTimeField(default=timezone.now)
    raw_html = models.TextField()
    html_diff = models.TextField(null=True, blank=True)
    text_diff = models.TextField(null=True, blank=True)
    previous_diff = models.ForeignKey(
        "self",
        on_delete=models.SET_NULL,
        related_name="_next_diff",
        null=True,
        blank=True,
    )
    next_diff = models.ForeignKey(
        "self",
        on_delete=models.SET_NULL,
        related_name="_prev_diff",
        null=True,
        blank=True,
    )

    USER_AGENT = (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36"
    )
    HEADERS = {"User-Agent": USER_AGENT, "Content-Type": "text/html"}

    def save(self, *args, **kwargs):
        # update_source = not self.pk
        timestamp = timezone.localtime()
        if not self.pk:
            # update source last checked
            self.source.last_checked = timestamp
            self.source.save()

            # get last pull
            source_pulls = SourceDetail.objects.filter(source=self.source).order_by(
                "-date_pulled"
            )
            if source_pulls.count():
                self.previous_diff = source_pulls.first()

            # grab html
            self.pull_html()

            # compare
            if self.previous_diff:
                self.compare_html()

                if not self.text_diff:
                    # Don't save if there aren't diffs
                    # todo: testing around this
                    return None
            self.date_pulled = timestamp
        super(SourceDetail, self).save(*args, **kwargs)

        if self.previous_diff:
            self.previous_diff.next_diff = self
            self.previous_diff.save()
            # todo: add testing around ^

    def pull_html(self):
        response = requests.get(self.source.url, self.HEADERS)
        if response.status_code != 200:
            # do something
            pass
        else:
            self.raw_html = response.text

    def compare_html(self):
        new_soup = list(BeautifulSoup(self.raw_html, "html.parser").stripped_strings)
        old_soup = list(
            BeautifulSoup(self.previous_diff.raw_html, "html.parser").stripped_strings
        )
        self.html_diff = difflib.HtmlDiff().make_file(
            old_soup, new_soup, context=True, numlines=5
        )
        self.text_diff = "".join(difflib.unified_diff(old_soup, new_soup))

    def get_absolute_url(self):
        return reverse(
            "sources:diff", kwargs={"pk": self.pk, "source_pk": self.source.pk}
        )

    class Meta:
        ordering = ["-date_pulled"]


class Fips(models.Model):
    fips = models.CharField(max_length=5, blank=False, null=False)
    county = models.CharField(max_length=255, blank=False, null=False)
    state = models.CharField(choices=STATES, max_length=2, blank=False, null=False)

    class Meta:
        verbose_name_plural = "Fips"
        ordering = ["fips"]

ballot_source/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for Ballot Source.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

ballot_source/sources/forms.py
import requests
from django import forms
from django.core.exceptions import ValidationError

from .models import Source


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = ["url", "source_type", "fips", "state"]

    def clean_url(self):
        self.cleaned_data = super(SourceForm, self).clean()
        url = self.cleaned_data["url"]

        Source.validate_url(url)

        try:
            requests.get(url)
        except requests.exceptions.ConnectionError:
            raise ValidationError(
                "The url does not appear to be working. Check the spelling and try again."
            )
        return url

ballot_source/users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

ballot_source/sources/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import reverse
from django.urls import reverse_lazy
from django.views.generic import (
    DetailView,
    FormView,
    ListView,
    TemplateView,
    UpdateView,
    View,
)

from .forms import SourceForm
from .models import Source, SourceDetail


class SourceListView(LoginRequiredMixin, ListView):
    model = Source


class SourceDetailView(LoginRequiredMixin, DetailView):
    model = Source
    ordering = ["-last_checked"]


class SourceFormView(LoginRequiredMixin, FormView):
    form_class = SourceForm
    template_name = "sources/source_create.html"
    success_url = reverse_lazy("sources:detail")

    def form_valid(self, form):
        source = form.save()
        self.pk = source.pk
        self.add_another = True if form.data.get("add_another", False) else False
        return super(SourceFormView, self).form_valid(form)

    def get_success_url(self, **kwargs):
        if self.add_another:
            return reverse("sources:new")
        return reverse("sources:detail", kwargs={"pk": self.pk})


class SourceEditView(LoginRequiredMixin, UpdateView):
    form_class = SourceForm
    template_name = "sources/source_create.html"

    def get_object(self, queryset=None):
        obj = Source.objects.get(pk=self.kwargs["pk"])
        return obj


class ManageSubscriptions(LoginRequiredMixin, View):
    def dispatch(self, request, *args, **kwargs):
        """
        Overrides http method using action from data
        """
        self.json_response = {"source_pk": None, "status": None, "action": None}

        try:
            if request.method == "GET":
                self.source = Source.objects.get(pk=request.GET.get("pk", None))
            else:
                self.source = Source.objects.get(pk=request.POST.get("pk", None))
        except Source.DoesNotExist:
            self.json_response["status"] = "Source matching pk does not exist"
            return JsonResponse(self.json_response)
        self.json_response["source_pk"] = self.source.pk

        if request.method == "GET":
            self.json_response["action"] = request.method
            return super(ManageSubscriptions, self).dispatch(request, *args, **kwargs)

        request.method = request.POST.get("action", "POST").upper()
        self.json_response["action"] = request.method

        return super(ManageSubscriptions, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        self.json_response["status"] = (
            request.user in self.source.user_subscription.all()
        )
        return JsonResponse(self.json_response)

    def post(self, request, *args, **kwargs):
        if request.user not in self.source.user_subscription.all():
            self.source.user_subscription.add(request.user)
            self.json_response["status"] = "subscribed"
        else:
            self.json_response["status"] = "already subscribed"
        return JsonResponse(self.json_response)

    def delete(self, request, *args, **kwargs):
        if request.user not in self.source.user_subscription.all():
            self.json_response["status"] = "user is not subscribed"
        else:
            self.source.user_subscription.remove(request.user)
            self.json_response["status"] = "unsubscribed"
        return JsonResponse(self.json_response)


class DiffView(LoginRequiredMixin, DetailView):
    model = SourceDetail
    context_object_name = "diff"
    template_name = "sources/diff_detail.html"


class ScrapeView(LoginRequiredMixin, TemplateView):
    template_name = "sources/scrape.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if context.get("pk", None):
            source = Source.objects.get(pk=context.get("pk"))
            context["source"] = source
            source.scrape()
            if source.details.first().date_pulled == source.last_checked:
                context["changes"] = [source]
        else:
            changes = []
            for source in Source.objects.all():
                # self.stdout.write(self.style.NOTICE(f"Scraping {source}"))
                source.scrape()
                # msg = "Success: No differences found"

                if source.details.first().date_pulled == source.last_checked:
                    # msg = "Success: Differences found"
                    changes.append(source)

            context["changes"] = changes
        return context


class SubscriptionList(LoginRequiredMixin, ListView):
    model = Source
    template_name = "sources/subscription_list.html"
    context_object_name = "sources"

    def get_queryset(self):
        queryset = super(SubscriptionList, self).get_queryset()
        queryset = queryset.filter(user_subscription__in=[self.request.user])
        return queryset

ballot_source/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

ballot_source/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Ballot Source{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Ballot Drop source ">
    <meta name="author" content="PJ Hoberman">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}

    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet">


    {% endblock %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">Ballot Source</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Sources
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'sources:index' %}">Sources</a>
                <a class="dropdown-item" href="{% url 'sources:new' %}">Add new source</a>
                <a class="dropdown-item" href="{% url 'sources:subscriptions' %}">Manage subscriptions</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'sources:scrape' %}">Scrape</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->


      <!-- place project specific Javascript in this file -->
      <script type="text/javascript">
        const urls = {};
        urls['subscribe'] = "{% url 'sources:subscribe' %}";
        $.ajaxSetup({
          beforeSend: function(xhr) {
            xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
          },
        });
      </script>

      <script src="{% static 'js/project.js' %}"></script>


    {% endblock javascript %}
  </body>
</html>